on: push

jobs:
  sendMessage:
    name: Send Message
    runs-on: ubuntu-latest

    steps:
      - run: "curl -H \"Content-Type: application/json\" -d '
      {
        \"embeds\": [
          {
            \"title\": \"${{ github.action }}\"
          }
        ]
      }'
      -X POST https://discord.com/api/webhooks/779046008684412979/UaQqJmOHg7nwqNAupSc04_hiE-Hmrk61VwTwtgMEnuLcXFe95S29omkXHE-ikOzNk5bZ"