on: push


jobs:
  sendMessage:
    name: Send Message
    runs-on: ubuntu-latest

    steps:
      - name: "sendmmm"
        env:
          MSG: '{"title": "${{ github.event_name }} - ${{ job.status }}", "description": "In repository: ${{ github.repository }}"}'
        run: 'curl -H "Content-Type: application/json" -d "{"embeds": [$MSG]}" -X POST https://discord.com/api/webhooks/779046008684412979/UaQqJmOHg7nwqNAupSc04_hiE-Hmrk61VwTwtgMEnuLcXFe95S29omkXHE-ikOzNk5bZ'
      
      - name: "aa"
        env:
          THING: "THE_THING_VALUE"
        run: "echo $THING"
