on: push

message: &msg '{
  "embeds": [
    {
      "title": "${{ github.event_name }} - ${{ job.status }}",
      "description": "In repository: ${{ github.repository }}"
    }
  ]
}'


jobs:
  sendMessage:
    name: Send Message
    runs-on: ubuntu-latest

    steps:
      - run: !join ['curl -H "Content-Type: application/json" -d ', *msg, ' -X POST https://discord.com/api/webhooks/779046008684412979/UaQqJmOHg7nwqNAupSc04_hiE-Hmrk61VwTwtgMEnuLcXFe95S29omkXHE-ikOzNk5bZ']