name: "Use The Action"
on: push

jobs:
  useTheAction:
    name: AA
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: "aaaaaaaa"
        uses: ./.github/actions/discord-notifier/