on: push


jobs:
  useTheAction:
    name: AA
    runs-on: ubuntu-18.04

    steps:
      - name: "aaaaaaaa"
        uses: ItayNaveh/MyDiscordNotifier@testing3
        with:
          webhook-id: ""
          webhook-token: ""