name: "Use The Action"
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Setup Node"
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      # - name: "Install Dependencies"
      #   run: "npm ci"

      - name: build
        id: build
        run: "npm run build"

    outputs:
      status: "${{ steps.build.outcome }}"

  sendMessage:
    name: "Send Message"
    runs-on: ubuntu-18.04

    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "aaaaaaaa"
        uses: ./.github/actions/discord-notifier/
        with:
          status: ${{ needs.build.outputs.status }}